### ISSUE TITLE
🚀 Feature Request: Full-height iframe in LivestreamDetailsModal

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#198]
### Describe the solution

(This is more a question than a suggestion.)

I am wondering if, when the LivestreamDetailsModal has a column layout (i.e. when the screen is sufficiently wide), it could be beneficial to make the iframe take up the full height of the modal instead of limiting its height to 9/16ths of its width.

Benefits:
1. Non-16:9 videos, especially vertical videos, would be shown in the largest dimensions possible since we would use all the available screen real estate. Below is a comparison.
![image](https://github.com/sugar-cat7/vspo-portal/assets/155891765/84f1071d-0e4d-432b-a122-0ea3bc41c4ea)
![image](https://github.com/sugar-cat7/vspo-portal/assets/155891765/fe09f5b9-0f13-4685-9ab9-59c2233ea584)

2. Twitcasts would not awkwardly be contained in a 16:9 iframe.
![image](https://github.com/sugar-cat7/vspo-portal/assets/155891765/ff249b5c-34a9-4986-986e-ba0f80adaa9e)
![image](https://github.com/sugar-cat7/vspo-portal/assets/155891765/9ddd8da3-4569-49a3-90b5-16172917e1ad)

I do not see any clear drawbacks, especially since both Twitch and YouTube seem to handle iframe dimensions which do not align with the video's aspect ratio.
![image](https://github.com/sugar-cat7/vspo-portal/assets/155891765/a6cc5b65-e14b-4b88-807a-803d816ad31c)

**Comment by sugar-cat7** [comment]
I agree! 
Indeed, when viewed on a PC, the extra space below the iframe is quite noticeable. (With the increase in vertical broadcasts, I think this is worth doing.)

**Comment by ss77995ss** [comment]
Full height looks great! However, if we want to apply it we may not use `<YouTubeEmbed>` which is mentioned in #29 

The reason is it will generate a wrapper and its **size** (width & height) could only be **number** or `auto` since the component prop type is set to `number | undefined`.

<img width="541" alt="Screenshot 2024-02-18 at 11 28 53" src="https://github.com/sugar-cat7/vspo-portal/assets/28031139/250d1691-d2ce-41f0-8809-0d1f71d644e0">

If we want to implement **full-height** we might need to do some workaround which I think it will be a little messy.
Besides, I have already done some workaround to make the Video UIs look the same while adding `<YouYubeEmbed>` and actually I don't really like it :(

Also, some functionalities like cover image lazy loading are missing. (ref: https://github.com/paulirish/lite-youtube-embed/issues/57)

Maybe we can keep `<ResponsiveIframe>` solution until we meet performance issue then see how `<YouTubeEmbed>` enhance solve the problem and create our own one

**Comment by sugar-cat7** [comment]
>Do you mind sharing the motivation for https://github.com/sugar-cat7/vspo-portal/issues/29,

The motivation behind raising this issue was the hope of eliminating the logic for assembling URLs and gaining typed options by stopping the construction of iframe components on our own. 
(However, I recognize that since we still need to create our own iframes for platforms other than YouTube, such as Twitch, tackling YouTube alone might not be very effective.)

As everyone has verified, if the Fragment is the reason it's difficult to handle with MUI styling, I believe it's fine to continue using the existing approach. :)

**Comment by ss77995ss** [comment]
Yeah another benefit of using iframe is we can do customization for different components easily 👍
I can take this one if you don't mind.

**Comment by sugar-cat7** [comment]
Yes, let's put #29 on hold for now. 

Feel free to adjust the assignment of tasks or break them down in a way that's most convenient for everyone!
